default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: mydb
<<<<<<< HEAD

=======
>>>>>>> cbb8985f37cb571bba4536b814d193f5f6722788
test:
  <<: *default
  database: mydb

production:
  <<: *default
  database: mydb
<<<<<<< HEAD
  username: root
  password:
=======
  username: reading_book
  password: <%= ENV["READING_BOOK_DATABASE_PASSWORD"] %>
>>>>>>> cbb8985f37cb571bba4536b814d193f5f6722788
