default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: mydb_production

test:
  <<: *default
  database: mydb_production

production:
  <<: *default
  database: mydb_production
  username: root
  password:
